### ISSUE TITLE
Error: Intune Workload: Update-MSGraphEnvironment is not recognized as the name of a cmdlet,

### ISSUE THREAD

**Issue by William-Francillette** [microsoft/MSCloudLoginAssistant#140]
When using the the Intune workload I receive the following error
```
System.Management.Automation.CommandNotFoundException: The term 'Update-MSGraphEnvironment' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error retrieving data:"
at Connect-MSCloudLoginIntune, C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.103\Workloads\Intune.psm1: line 67
at Connect, C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.103\ConnectionProfile.psm1: line 327
at Connect-M365Tenant, C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.103\MSCloudLoginAssistant.psm1: line 206
at New-M365DSCConnection, C:\DevOps\Microsoft365DSC-1\Modules\Microsoft365Dsc\modules\M365DSCUtil.psm1: line 1816
at Get-TargetResource, C:\DevOps\Microsoft365DSC-1\Modules\Microsoft365DSC\DSCResources\MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled\MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled.psm1: line 143
at <ScriptBlock>, <No file>: line 2


```

If I use the Graph workload I don't have the issue

**Comment by FabienTschanz** [comment]
This functionality is no longer part of MSCloudLoginAssistant.
